export const samples = {
  meta: {
    name: "hello world sample",
    fps: 30,
    width: 1920,
    height: 1080,
  },
  layers: [
    {
      id: "t1",
      type: "text",
      startMs: 0,
      durationMs: 1500,
      payload: {
        text: "Dream big",
        animations: [
          {
            startMs: 0,
            endMs: 700,
            cssProperties: {
              width: 100,
              height: 100,
              backgroundColor: "#ff0000",
              opacity: 1,
              transform: "rotate(0deg)",
              fontFamily: "Bebas Neue, Impact, sans-serif",
              fontSize: 120,
            },
          },
          {
            startMs: 700,
            endMs: 1500,
            cssProperties: {
              width: 300,
              height: 150,
              backgroundColor: "#0000ff",
              opacity: 0.5,
              transform: "rotate(45deg)",
              fontFamily: "Bebas Neue, Impact, sans-serif",
              fontSize: 80,
            },
          },
        ],
      },
    },
  ],
};

export const samples2 = {
  name: "Mastering Minimalism in 90 Seconds",
  layers: [
    {
      id: "t1",
      type: "text",
      startMs: 0.0,
      durationMs: 17159.99984741211,
      payload: {
        text: "Welcome to the minimalist revolution. In the next 90 seconds, we're going to strip down the chaos and embrace the beauty of simplicity. Buckle up, because this is going to be a smooth ride.",
        animations: [
          {
            startMs: 0,
            endMs: 400,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 400,
            endMs: 16759.99984741211,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 1,
              transform: "translateY(0) scale(1)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 16759.99984741211,
            endMs: 17159.99984741211,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(-30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
        ],
      },
    },
    {
      id: "t2",
      type: "text",
      startMs: 17209.99984741211,
      durationMs: 17299.999237060547,
      payload: {
        text: "Ever heard the phrase 'less is more'? Well, in design it's not just a saying—it's a lifestyle. Minimalism is like the Marie Kondo of aesthetics, sparking joy with every clean line and empty space.",
        animations: [
          {
            startMs: 0,
            endMs: 400,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 400,
            endMs: 16899.999237060547,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 1,
              transform: "translateY(0) scale(1)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 16899.999237060547,
            endMs: 17299.999237060547,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(-30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
        ],
      },
    },
    {
      id: "t3",
      type: "text",
      startMs: 34559.999084472656,
      durationMs: 23239.999771118164,
      payload: {
        text: "Let's talk colors. Our palette is like a superhero team—it has a leader and a sidekick. 3D3 is the flashy one, and C700 3D9 adds that mysterious depth. Together they create visual harmony.",
        animations: [
          {
            startMs: 0,
            endMs: 400,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 400,
            endMs: 22839.999771118164,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 1,
              transform: "translateY(0) scale(1)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 22839.999771118164,
            endMs: 23239.999771118164,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(-30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
        ],
      },
    },
    {
      id: "t4",
      type: "text",
      startMs: 57849.99885559082,
      durationMs: 12319.999694824219,
      payload: {
        text: "Animations are the unsung heroes of video. With smooth fade-ins and fade-outs, they keep your eyes glued to the screen like a cat watching a laser pointer.",
        animations: [
          {
            startMs: 0,
            endMs: 400,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 400,
            endMs: 11919.999694824219,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 1,
              transform: "translateY(0) scale(1)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 11919.999694824219,
            endMs: 12319.999694824219,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(-30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
        ],
      },
    },
    {
      id: "t5",
      type: "text",
      startMs: 70219.99855041504,
      durationMs: 14680.000305175781,
      payload: {
        text: "Key points deserve the spotlight, and pop-up text is like the neon sign saying, 'Hey, look at me.' It's all about making sure the important stuff doesn't get lost in the shuffle.",
        animations: [
          {
            startMs: 0,
            endMs: 400,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 400,
            endMs: 14280.000305175781,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 1,
              transform: "translateY(0) scale(1)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 14280.000305175781,
            endMs: 14680.000305175781,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(-30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
        ],
      },
    },
    {
      id: "t6",
      type: "text",
      startMs: 84949.99885559082,
      durationMs: 12840.00015258789,
      payload: {
        text: "Line animations are like the GPS for your eyes, guiding you through the content without missing a beat. It's like having a personal tour guide in video form.",
        animations: [
          {
            startMs: 0,
            endMs: 400,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 400,
            endMs: 12440.00015258789,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 1,
              transform: "translateY(0) scale(1)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 12440.00015258789,
            endMs: 12840.00015258789,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(-30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
        ],
      },
    },
    {
      id: "t7",
      type: "text",
      startMs: 97839.99900817871,
      durationMs: 13100.000381469727,
      payload: {
        text: "Consistent pacing is the secret sauce of engaging videos. With synchronized music, it's like a perfectly timed dance routine that keeps you tapping your foot along.",
        animations: [
          {
            startMs: 0,
            endMs: 400,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 400,
            endMs: 12700.000381469727,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 1,
              transform: "translateY(0) scale(1)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 12700.000381469727,
            endMs: 13100.000381469727,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(-30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
        ],
      },
    },
    {
      id: "t8",
      type: "text",
      startMs: 110989.99938964844,
      durationMs: 14500,
      payload: {
        text: "And now, the grand finale. If you loved this minimalist journey, smash that subscribe button and join the revolution. Remember, less is more, but subscribing is everything.",
        animations: [
          {
            startMs: 0,
            endMs: 400,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 400,
            endMs: 14100,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 1,
              transform: "translateY(0) scale(1)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
          {
            startMs: 14100,
            endMs: 14500,
            cssProperties: {
              width: 1000,
              height: 200,
              backgroundColor: "#ffffff",
              opacity: 0,
              transform: "translateY(-30px) scale(0.95)",
              fontFamily: "Inter, Helvetica, sans-serif",
              fontSize: 72,
            },
          },
        ],
      },
    },
  ],
};
