export const sample2 = {
  runId: "d1eqvtqe",
  result: {
    meta: {
      fps: 30,
      width: 1920,
      height: 1080,
      durationInFrames: 360,
    },
    files: {
      "Main.tsx":
        'import { Composition } from "remotion";\nimport { GomotionIntro } from "./GomotionIntro";\nimport { GomotionTheme } from "./GomotionTheme";\n\nexport const RemotionRoot: React.FC = () => {\n  return (\n    <>\n      <Composition\n        id="GomotionIntro"\n        component={GomotionIntro}\n        durationInFrames={GomotionTheme.totalDuration}\n        fps={GomotionTheme.fps}\n        width={GomotionTheme.width}\n        height={GomotionTheme.height}\n      />\n    </>\n  );\n};\n',
      "GomotionTheme.ts":
        'export const GomotionTheme = {\n  width: 1920,\n  height: 1080,\n  fps: 30,\n  totalDuration: 360,\n  colors: {\n    background: "#0A0A0A",\n    primary: "#FFFFFF",\n    secondary: "#A0A0A0",\n    accent: "#4CAF50",\n  },\n  typography: {\n    headline: {\n      fontSize: 120,\n      fontWeight: 700,\n      lineHeight: 1.1,\n    },\n    subhead: {\n      fontSize: 48,\n      fontWeight: 400,\n      lineHeight: 1.3,\n    },\n  },\n  motion: {\n    easeInOut: "power2.inOut",\n    easeOut: "power3.out",\n    stagger: 0.1,\n    durationShort: 0.6,\n    durationMedium: 1.2,\n  },\n};\n',
      "GomotionIntro.tsx":
        'import { Sequence, useVideoConfig } from "remotion";\nimport { loadFont } from "@remotion/google-fonts/Inter";\nimport { GomotionTheme } from "./GomotionTheme";\nimport { Background } from "./components/Background";\nimport { LogoAnimation } from "./components/LogoAnimation";\nimport { SubtitleAnimation } from "./components/SubtitleAnimation";\nimport { OutroAnimation } from "./components/OutroAnimation";\n\nconst { fontFamily } = loadFont();\n\nexport const GomotionIntro: React.FC = () => {\n  const { fps } = useVideoConfig();\n\n  // Sequence durations in frames\n  const DUR_INTRO = 2 * fps; // 60 frames\n  const DUR_FEATURE = 3 * fps; // 90 frames\n  const DUR_DETAIL = 3 * fps; // 90 frames\n  const DUR_CTA = 2 * fps; // 60 frames\n  const DUR_OUTRO = 2 * fps; // 60 frames\n\n  const total = DUR_INTRO + DUR_FEATURE + DUR_DETAIL + DUR_CTA + DUR_OUTRO;\n  if (total !== GomotionTheme.totalDuration) {\n    console.warn("Total duration mismatch");\n  }\n\n  return (\n    <div\n      style={{\n        fontFamily,\n        backgroundColor: GomotionTheme.colors.background,\n        width: "100%",\n        height: "100%",\n        display: "flex",\n        flexDirection: "column",\n        alignItems: "center",\n        justifyContent: "center",\n        position: "relative",\n        overflow: "hidden",\n      }}\n    >\n      <Background />\n\n      <Sequence from={0} durationInFrames={DUR_INTRO + DUR_FEATURE}>\n        <LogoAnimation />\n      </Sequence>\n\n      <Sequence from={DUR_INTRO + DUR_FEATURE} durationInFrames={DUR_DETAIL}>\n        <SubtitleAnimation text="Our Motion Designer Agent" />\n      </Sequence>\n\n      <Sequence from={DUR_INTRO + DUR_FEATURE + DUR_DETAIL} durationInFrames={DUR_CTA + DUR_OUTRO}>\n        <OutroAnimation />\n      </Sequence>\n    </div>\n  );\n};\n',
      "useGsapTimeline.ts":
        'import gsap from "gsap";\nimport { useEffect, useRef } from "react";\nimport { useCurrentFrame, useVideoConfig } from "remotion";\n\nexport const useGsapTimeline = <T extends HTMLElement>(\n  gsapTimelineFactory: () => gsap.core.Timeline,\n) => {\n  const animationScopeRef = useRef<T>(null);\n  const timelineRef = useRef<gsap.core.Timeline>(null);\n\n  const frame = useCurrentFrame();\n  const { fps } = useVideoConfig();\n\n  useEffect(() => {\n    const ctx = gsap.context(() => {\n      timelineRef.current = gsapTimelineFactory();\n      timelineRef.current.pause();\n    }, animationScopeRef);\n    return () => ctx.revert();\n  }, []);\n\n  useEffect(() => {\n    if (timelineRef.current) {\n      timelineRef.current.seek(frame / fps);\n    }\n  }, [frame, fps]);\n\n  return animationScopeRef;\n};\n',
      "components/Background.tsx":
        'import { AbsoluteFill } from "remotion";\nimport { GomotionTheme } from "../GomotionTheme";\n\nexport const Background: React.FC = () => {\n  return (\n    <AbsoluteFill\n      style={{\n        background: `linear-gradient(135deg, ${GomotionTheme.colors.background} 0%, #1A1A1A 100%)`,\n        opacity: 1,\n      }}\n    />\n  );\n};\n',
      "components/LogoAnimation.tsx":
        'import gsap from "gsap";\nimport { useRef } from "react";\nimport { GomotionTheme } from "../GomotionTheme";\nimport { useGsapTimeline } from "../useGsapTimeline";\n\nexport const LogoAnimation: React.FC = () => {\n  const scopeRef = useGsapTimeline(() => {\n    const tl = gsap.timeline();\n    tl.from(".logo-letter", {\n      y: 100,\n      opacity: 0,\n      duration: GomotionTheme.motion.durationMedium,\n      ease: GomotionTheme.motion.easeOut,\n      stagger: GomotionTheme.motion.stagger,\n    });\n    tl.to(".logo-letter", {\n      scale: 1.02,\n      duration: 0.3,\n      ease: "power1.inOut",\n      repeat: 1,\n      yoyo: true,\n      delay: 0.5,\n    });\n    return tl;\n  });\n\n  const letters = "Gomotion".split("");\n\n  return (\n    <div\n      ref={scopeRef}\n      style={{\n        display: "flex",\n        alignItems: "center",\n        justifyContent: "center",\n        fontSize: GomotionTheme.typography.headline.fontSize,\n        fontWeight: GomotionTheme.typography.headline.fontWeight,\n        color: GomotionTheme.colors.primary,\n        letterSpacing: "0.05em",\n      }}\n    >\n      {letters.map((letter, index) => (\n        <span key={index} className="logo-letter">\n          {letter}\n        </span>\n      ))}\n    </div>\n  );\n};\n',
      "components/OutroAnimation.tsx":
        'import gsap from "gsap";\nimport { GomotionTheme } from "../GomotionTheme";\nimport { useGsapTimeline } from "../useGsapTimeline";\n\nexport const OutroAnimation: React.FC = () => {\n  const scopeRef = useGsapTimeline(() => {\n    const tl = gsap.timeline();\n    tl.fromTo(\n      ".outro",\n      { scale: 0.5, opacity: 0 },\n      {\n        scale: 1,\n        opacity: 1,\n        duration: GomotionTheme.motion.durationMedium,\n        ease: GomotionTheme.motion.easeOut,\n      }\n    );\n    tl.to(".outro", {\n      opacity: 0,\n      duration: 1,\n      delay: 1,\n    });\n    return tl;\n  });\n\n  return (\n    <div\n      ref={scopeRef}\n      style={{\n        position: "absolute",\n        top: 0,\n        left: 0,\n        width: "100%",\n        height: "100%",\n        display: "flex",\n        alignItems: "center",\n        justifyContent: "center",\n        fontSize: 36,\n        color: GomotionTheme.colors.accent,\n        backgroundColor: "rgba(0,0,0,0.3)",\n      }}\n    >\n      <span className="outro">Powered by Gomotion</span>\n    </div>\n  );\n};\n',
      "components/SubtitleAnimation.tsx":
        'import gsap from "gsap";\nimport { GomotionTheme } from "../GomotionTheme";\nimport { useGsapTimeline } from "../useGsapTimeline";\n\nexport const SubtitleAnimation: React.FC<{ text: string }> = ({ text }) => {\n  const scopeRef = useGsapTimeline(() => {\n    const tl = gsap.timeline();\n    tl.from(".subtitle", {\n      x: -50,\n      opacity: 0,\n      duration: GomotionTheme.motion.durationShort,\n      ease: GomotionTheme.motion.easeInOut,\n    });\n    tl.to(".subtitle", {\n      x: 0,\n      duration: GomotionTheme.motion.durationMedium,\n    });\n    return tl;\n  });\n\n  return (\n    <div\n      ref={scopeRef}\n      style={{\n        position: "absolute",\n        bottom: 200,\n        fontSize: GomotionTheme.typography.subhead.fontSize,\n        fontWeight: GomotionTheme.typography.subhead.fontWeight,\n        color: GomotionTheme.colors.secondary,\n      }}\n    >\n      <span className="subtitle">{text}</span>\n    </div>\n  );\n};\n',
    },
    title: "Gomotion Introduction Animation",
  },
};
