export const mock = {
  id: "a27774ca-5e2b-46b5-bcc5-7db2d8b99cf2",
  created_at: "2025-06-24T12:14:34.376163+00:00",
  composition: {
    src: {
      directory: {
        "App.tsx": {
          file: {
            contents:
              "import React from 'react';\nimport { Player } from '@remotion/player';\nimport { DynamicMontage } from './components/DynamicMontage';\n\nconst App: React.FC = () => {\n  return (\n    <div>\n      <Player\n        component={DynamicMontage}\n        durationInFrames={1800}\n        fps={30}\n        compositionWidth={1920}\n        compositionHeight={1080}\n        controls\n        style={{ width: '100%' }}\n      />\n    </div>\n  );\n};\n\nexport default App;",
          },
        },
        "main.tsx": {
          file: {
            contents:
              "import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\n\nReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);",
          },
        },
        components: {
          directory: {
            "OnScreenText.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { interpolate, useCurrentFrame, spring, useVideoConfig } from 'remotion';\n\ntype OnScreenTextProps = {\n  text: string;\n  animationTiming: number;\n  textColor: string;\n  backgroundColor: string;\n  fontSize: string;\n  fontWeight: string;\n  textAlign: 'left' | 'center' | 'right';\n  fontFamily: string;\n};\n\nconst OnScreenText: React.FC<OnScreenTextProps> = ({\n  text,\n  animationTiming,\n  textColor,\n  backgroundColor,\n  fontSize,\n  fontWeight,\n  textAlign,\n  fontFamily,\n}) => {\n  const frame = useCurrentFrame();\n  const { fps } = useVideoConfig();\n\n  const opacity = interpolate(\n    frame,\n    [0, animationTiming * fps],\n    [0, 1],\n    {\n      extrapolateLeft: 'clamp',\n      extrapolateRight: 'clamp',\n    }\n  );\n\n  const translateY = spring({\n    frame,\n    fps,\n    from: 50,\n    to: 0,\n    durationInFrames: animationTiming * fps,\n  });\n\n  return (\n    <div\n      style={{\n        display: 'flex',\n        justifyContent: textAlign,\n        alignItems: 'center',\n        height: '100%',\n        backgroundColor,\n        color: textColor,\n        fontSize,\n        fontWeight,\n        fontFamily,\n        opacity,\n        transform: `translateY(${translateY}px)`,\n      }}\n    >\n      {text}\n    </div>\n  );\n};\n\nexport default OnScreenText;\n```",
              },
            },
            "FuturisticLab.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, Sequence } from 'remotion';\n\ntype FuturisticLabProps = {\n  scientistsCount: number;\n  sceneMood: 'mysterious' | 'ominous';\n  aiBrainGlowColor: string;\n  textContent: string;\n  animationDuration: number;\n};\n\nconst FuturisticLab: React.FC<FuturisticLabProps> = ({\n  scientistsCount,\n  sceneMood,\n  aiBrainGlowColor,\n  textContent,\n  animationDuration,\n}) => {\n  const frame = useCurrentFrame();\n  const opacity = interpolate(frame, [0, animationDuration * 30], [0, 1]);\n  const glowIntensity = interpolate(frame, [0, animationDuration * 30], [0, 1]);\n\n  const moodStyles = {\n    mysterious: {\n      backgroundColor: 'rgba(0, 0, 50, 0.8)',\n      color: 'white',\n    },\n    ominous: {\n      backgroundColor: 'rgba(50, 0, 0, 0.8)',\n      color: 'red',\n    },\n  };\n\n  return (\n    <div style={{ ...moodStyles[sceneMood], width: '100%', height: '100%', position: 'relative' }}>\n      <div\n        style={{\n          position: 'absolute',\n          top: '50%',\n          left: '50%',\n          transform: 'translate(-50%, -50%)',\n          width: '200px',\n          height: '200px',\n          borderRadius: '50%',\n          backgroundColor: 'black',\n          boxShadow: `0 0 30px ${aiBrainGlowColor}`,\n          opacity: glowIntensity,\n        }}\n      />\n      <div\n        style={{\n          position: 'absolute',\n          bottom: '10%',\n          width: '100%',\n          textAlign: 'center',\n          fontSize: '24px',\n          opacity,\n        }}\n      >\n        {textContent}\n      </div>\n      <div\n        style={{\n          position: 'absolute',\n          top: '10%',\n          left: '10%',\n          fontSize: '18px',\n          color: 'white',\n          opacity,\n        }}\n      >\n        {`Scientists: ${scientistsCount}`}\n      </div>\n    </div>\n  );\n};\n\nexport default FuturisticLab;\n```",
              },
            },
            "SpinningGlobe.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, Sequence, Img } from 'remotion';\n\ntype SpinningGlobeProps = {\n  globeSpeed: number;\n  aiIconUrls: string[];\n  transitionDuration: number;\n  cityscapeImageUrl: string;\n  textContent: string;\n  textColor: string;\n};\n\nconst SpinningGlobe: React.FC<SpinningGlobeProps> = ({\n  globeSpeed,\n  aiIconUrls,\n  transitionDuration,\n  cityscapeImageUrl,\n  textContent,\n  textColor,\n}) => {\n  const frame = useCurrentFrame();\n\n  const globeRotation = interpolate(\n    frame,\n    [0, 100],\n    [0, 360 * globeSpeed],\n    { extrapolateRight: 'clamp' }\n  );\n\n  const transitionOpacity = interpolate(\n    frame,\n    [100, 100 + transitionDuration],\n    [0, 1],\n    { extrapolateLeft: 'clamp' }\n  );\n\n  const textOpacity = interpolate(\n    frame,\n    [0, 30],\n    [0, 1],\n    { extrapolateRight: 'clamp' }\n  );\n\n  return (\n    <div style={{ flex: 1, position: 'relative', backgroundColor: 'black' }}>\n      <Sequence from={0} durationInFrames={100}>\n        <div\n          style={{\n            transform: `rotate(${globeRotation}deg)`,\n            width: '100%',\n            height: '100%',\n            background: 'url(./assets/globe.png) no-repeat center center',\n            backgroundSize: 'contain',\n            position: 'absolute',\n          }}\n        />\n        {aiIconUrls.map((url, index) => (\n          <Img\n            key={index}\n            src={url}\n            style={{\n              position: 'absolute',\n              top: `${Math.random() * 80 + 10}%`,\n              left: `${Math.random() * 80 + 10}%`,\n              width: '50px',\n              height: '50px',\n              opacity: textOpacity,\n            }}\n          />\n        ))}\n      </Sequence>\n      <Sequence from={100}>\n        <Img\n          src={cityscapeImageUrl}\n          style={{\n            width: '100%',\n            height: '100%',\n            opacity: transitionOpacity,\n            position: 'absolute',\n          }}\n        />\n        <div\n          style={{\n            position: 'absolute',\n            bottom: '10%',\n            width: '100%',\n            textAlign: 'center',\n            color: textColor,\n            fontSize: '2em',\n            opacity: transitionOpacity,\n          }}\n        >\n          {textContent}\n        </div>\n      </Sequence>\n    </div>\n  );\n};\n\nexport default SpinningGlobe;\n```",
              },
            },
            "DynamicMontage.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, Sequence, spring } from 'remotion';\n\ntype DynamicMontageProps = {\n  images: string[];\n  transitionEffect: string;\n  animationDuration: number;\n  textOverlay: string;\n  textStyle: React.CSSProperties;\n  backgroundColor: string;\n  zoomEffect: boolean;\n};\n\nconst DynamicMontage: React.FC<DynamicMontageProps> = ({\n  images,\n  transitionEffect,\n  animationDuration,\n  textOverlay,\n  textStyle,\n  backgroundColor,\n  zoomEffect,\n}) => {\n  const frame = useCurrentFrame();\n  const totalDuration = images.length * animationDuration * 30; // assuming 30 fps\n\n  const getTransitionStyle = (index: number) => {\n    const startFrame = index * animationDuration * 30;\n    const endFrame = startFrame + animationDuration * 30;\n\n    const opacity = interpolate(\n      frame,\n      [startFrame, startFrame + 15, endFrame - 15, endFrame],\n      [0, 1, 1, 0],\n      { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }\n    );\n\n    const transform = zoomEffect\n      ? `scale(${interpolate(frame, [startFrame, endFrame], [1, 1.1], {\n          extrapolateLeft: 'clamp',\n          extrapolateRight: 'clamp',\n        })})`\n      : 'scale(1)';\n\n    return {\n      opacity,\n      transform,\n      transition: transitionEffect === 'fade' ? 'opacity 0.5s' : 'transform 0.5s',\n    };\n  };\n\n  return (\n    <div style={{ backgroundColor, width: '100%', height: '100%', position: 'relative' }}>\n      {images.map((image, index) => (\n        <Sequence key={index} from={index * animationDuration * 30} durationInFrames={animationDuration * 30}>\n          <div\n            style={{\n              ...getTransitionStyle(index),\n              backgroundImage: `url(${image})`,\n              backgroundSize: 'cover',\n              backgroundPosition: 'center',\n              width: '100%',\n              height: '100%',\n              position: 'absolute',\n            }}\n          />\n        </Sequence>\n      ))}\n      <div\n        style={{\n          position: 'absolute',\n          bottom: '10%',\n          width: '100%',\n          textAlign: 'center',\n          ...textStyle,\n        }}\n      >\n        {textOverlay}\n      </div>\n    </div>\n  );\n};\n\nexport default DynamicMontage;\n```",
              },
            },
            "DetectiveFigure.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, spring, Img, Sequence } from 'remotion';\n\ntype DetectiveFigureProps = {\n  noteText: string;\n  figureImageUrl: string;\n  animationDuration: number;\n  position: { x: number; y: number };\n  themeColor: string;\n};\n\nconst DetectiveFigure: React.FC<DetectiveFigureProps> = ({\n  noteText,\n  figureImageUrl,\n  animationDuration,\n  position,\n  themeColor,\n}) => {\n  const frame = useCurrentFrame();\n  const springConfig = {\n    fps: 30,\n    damping: 10,\n    stiffness: 100,\n  };\n\n  const noteTakingProgress = spring({\n    frame,\n    fps: springConfig.fps,\n    config: springConfig,\n    durationInFrames: animationDuration * springConfig.fps,\n  });\n\n  const translateY = interpolate(noteTakingProgress, [0, 1], [50, 0]);\n  const opacity = interpolate(noteTakingProgress, [0, 1], [0, 1]);\n\n  return (\n    <div\n      style={{\n        position: 'absolute',\n        left: position.x,\n        top: position.y,\n        color: themeColor,\n        display: 'flex',\n        flexDirection: 'column',\n        alignItems: 'center',\n      }}\n    >\n      <Img\n        src={figureImageUrl}\n        style={{\n          width: 100,\n          height: 'auto',\n          marginBottom: 10,\n        }}\n      />\n      <Sequence from={0} durationInFrames={animationDuration * springConfig.fps}>\n        <div\n          style={{\n            transform: `translateY(${translateY}px)`,\n            opacity,\n            backgroundColor: themeColor,\n            padding: '10px',\n            borderRadius: '5px',\n            boxShadow: `0 0 10px ${themeColor}`,\n          }}\n        >\n          {noteText}\n        </div>\n      </Sequence>\n    </div>\n  );\n};\n\nexport default DetectiveFigure;\n```",
              },
            },
            "SmartphoneUsage.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, spring, Sequence } from 'remotion';\n\ntype SmartphoneUsageProps = {\n  personImageUrl: string;\n  appIcons: string[];\n  sceneBrightness: number;\n  animationTiming: number;\n  textContent: string;\n};\n\nconst SmartphoneUsage: React.FC<SmartphoneUsageProps> = ({\n  personImageUrl,\n  appIcons,\n  sceneBrightness,\n  animationTiming,\n  textContent,\n}) => {\n  const frame = useCurrentFrame();\n  const brightness = interpolate(sceneBrightness, [0, 1], [0.2, 1]);\n  const textOpacity = interpolate(frame, [0, 30], [0, 1]);\n\n  return (\n    <div\n      style={{\n        display: 'flex',\n        flexDirection: 'column',\n        alignItems: 'center',\n        justifyContent: 'center',\n        width: '100%',\n        height: '100%',\n        backgroundColor: `rgba(255, 255, 255, ${brightness})`,\n        position: 'relative',\n      }}\n    >\n      <img\n        src={personImageUrl}\n        alt=\"Person using smartphone\"\n        style={{\n          width: '50%',\n          height: 'auto',\n          borderRadius: '10px',\n          boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',\n        }}\n      />\n      <div\n        style={{\n          position: 'absolute',\n          bottom: '10%',\n          width: '80%',\n          textAlign: 'center',\n          color: '#333',\n          fontSize: '24px',\n          opacity: textOpacity,\n        }}\n      >\n        {textContent}\n      </div>\n      {appIcons.map((icon, index) => {\n        const float = spring({\n          frame: frame - index * 10,\n          fps: 30,\n          config: {\n            damping: 10,\n            stiffness: 100,\n            mass: 0.5,\n          },\n        });\n\n        const translateY = interpolate(float, [0, 1], [0, -50]);\n        const translateX = interpolate(float, [0, 1], [0, 50 * (index % 2 === 0 ? 1 : -1)]);\n\n        return (\n          <img\n            key={index}\n            src={icon}\n            alt={`App icon ${index}`}\n            style={{\n              position: 'absolute',\n              width: '50px',\n              height: '50px',\n              bottom: '20%',\n              left: `${20 + index * 10}%`,\n              transform: `translate(${translateX}px, ${translateY}px)`,\n              transition: `transform ${animationTiming}s ease-in-out`,\n            }}\n          />\n        );\n      })}\n    </div>\n  );\n};\n\nexport default SmartphoneUsage;\n```",
              },
            },
            "RoombaNavigation.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, Sequence, useVideoConfig } from 'remotion';\n\ninterface RoombaNavigationProps {\n  obstaclePositions: { x: number; y: number; }[];\n  roombaSpeed: number;\n  cameraFollow: boolean;\n  roomDimensions: { width: number; height: number; };\n  textContent: string;\n  animationDuration: number;\n}\n\nconst RoombaNavigation: React.FC<RoombaNavigationProps> = ({\n  obstaclePositions,\n  roombaSpeed,\n  cameraFollow,\n  roomDimensions,\n  textContent,\n  animationDuration,\n}) => {\n  const frame = useCurrentFrame();\n  const { fps } = useVideoConfig();\n\n  const totalFrames = animationDuration * fps;\n  const roombaPositionX = interpolate(\n    frame,\n    [0, totalFrames],\n    [0, roomDimensions.width],\n    { extrapolateRight: 'clamp' }\n  );\n\n  const roombaPositionY = interpolate(\n    frame,\n    [0, totalFrames],\n    [0, roomDimensions.height],\n    { extrapolateRight: 'clamp' }\n  );\n\n  const cameraStyle = cameraFollow\n    ? {\n        transform: `translate(${-roombaPositionX + roomDimensions.width / 2}px, ${-roombaPositionY + roomDimensions.height / 2}px)`,\n      }\n    : {};\n\n  return (\n    <div\n      style={{\n        width: roomDimensions.width,\n        height: roomDimensions.height,\n        overflow: 'hidden',\n        position: 'relative',\n        ...cameraStyle,\n      }}\n    >\n      <div\n        style={{\n          position: 'absolute',\n          left: roombaPositionX,\n          top: roombaPositionY,\n          width: 50,\n          height: 50,\n          backgroundColor: 'gray',\n          borderRadius: '50%',\n        }}\n      />\n      {obstaclePositions.map((obstacle, index) => (\n        <div\n          key={index}\n          style={{\n            position: 'absolute',\n            left: obstacle.x,\n            top: obstacle.y,\n            width: 30,\n            height: 30,\n            backgroundColor: 'brown',\n          }}\n        />\n      ))}\n      <div\n        style={{\n          position: 'absolute',\n          bottom: 10,\n          left: 10,\n          color: 'white',\n          backgroundColor: 'rgba(0, 0, 0, 0.5)',\n          padding: '5px 10px',\n          borderRadius: '5px',\n        }}\n      >\n        {textContent}\n      </div>\n    </div>\n  );\n};\n\nexport default RoombaNavigation;\n```",
              },
            },
            "CallToActionScreen.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, Sequence } from 'remotion';\n\ntype CallToActionScreenProps = {\n  backgroundImage: string;\n  buttonText: string;\n  notificationIcon: string;\n  textContent: string;\n  animationTiming: string;\n  themeColor: string;\n};\n\nconst CallToActionScreen: React.FC<CallToActionScreenProps> = ({\n  backgroundImage,\n  buttonText,\n  notificationIcon,\n  textContent,\n  animationTiming,\n  themeColor,\n}) => {\n  const frame = useCurrentFrame();\n  const opacity = interpolate(frame, [0, 30], [0, 1], {\n    extrapolateLeft: 'clamp',\n    extrapolateRight: 'clamp',\n  });\n\n  const translateY = interpolate(frame, [0, 30], [50, 0], {\n    extrapolateLeft: 'clamp',\n    extrapolateRight: 'clamp',\n  });\n\n  return (\n    <div\n      style={{\n        backgroundImage: `url(${backgroundImage})`,\n        backgroundSize: 'cover',\n        backgroundPosition: 'center',\n        width: '100%',\n        height: '100%',\n        display: 'flex',\n        flexDirection: 'column',\n        alignItems: 'center',\n        justifyContent: 'center',\n        color: themeColor,\n        textAlign: 'center',\n        padding: '20px',\n      }}\n    >\n      <Sequence from={0} durationInFrames={Infinity}>\n        <div\n          style={{\n            opacity,\n            transform: `translateY(${translateY}px)`,\n            transition: `opacity ${animationTiming}, transform ${animationTiming}`,\n          }}\n        >\n          <p style={{ fontSize: '24px', marginBottom: '20px' }}>{textContent}</p>\n          <button\n            style={{\n              backgroundColor: themeColor,\n              color: '#fff',\n              border: 'none',\n              padding: '10px 20px',\n              fontSize: '18px',\n              cursor: 'pointer',\n              display: 'flex',\n              alignItems: 'center',\n              gap: '10px',\n            }}\n          >\n            <img\n              src={notificationIcon}\n              alt=\"Notification Bell\"\n              style={{ width: '24px', height: '24px' }}\n            />\n            {buttonText}\n          </button>\n        </div>\n      </Sequence>\n    </div>\n  );\n};\n\nexport default CallToActionScreen;\n```",
              },
            },
            "FastPacedAnimation.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, Sequence, spring } from 'remotion';\n\ntype AIAgent = {\n  name: string;\n  imageUrl: string;\n  type: string;\n};\n\ntype FastPacedAnimationProps = {\n  aiAgents: AIAgent[];\n  animationSpeed: number;\n  pokedexStyle: {\n    backgroundColor: string;\n    textColor: string;\n  };\n  sceneText: string;\n};\n\nconst FastPacedAnimation: React.FC<FastPacedAnimationProps> = ({\n  aiAgents,\n  animationSpeed,\n  pokedexStyle,\n  sceneText,\n}) => {\n  const frame = useCurrentFrame();\n  const totalAgents = aiAgents.length;\n  const agentDuration = 30 / animationSpeed;\n\n  return (\n    <div\n      style={{\n        backgroundColor: pokedexStyle.backgroundColor,\n        color: pokedexStyle.textColor,\n        fontFamily: 'Arial, sans-serif',\n        padding: '20px',\n        borderRadius: '10px',\n        width: '400px',\n        margin: 'auto',\n        textAlign: 'center',\n      }}\n    >\n      <h2>{sceneText}</h2>\n      {aiAgents.map((agent, index) => {\n        const startFrame = index * agentDuration;\n        const endFrame = startFrame + agentDuration;\n        const opacity = interpolate(\n          frame,\n          [startFrame, startFrame + 10, endFrame - 10, endFrame],\n          [0, 1, 1, 0],\n          { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }\n        );\n\n        const scale = spring({\n          frame: frame - startFrame,\n          fps: 30,\n          config: {\n            damping: 200,\n            stiffness: 100,\n            mass: 0.5,\n          },\n        });\n\n        return (\n          <Sequence key={agent.name} from={startFrame} durationInFrames={agentDuration}>\n            <div\n              style={{\n                opacity,\n                transform: `scale(${scale})`,\n                transition: 'transform 0.5s',\n              }}\n            >\n              <img\n                src={agent.imageUrl}\n                alt={agent.name}\n                style={{ width: '100px', height: '100px', borderRadius: '50%' }}\n              />\n              <h3>{agent.name}</h3>\n              <p>Type: {agent.type}</p>\n            </div>\n          </Sequence>\n        );\n      })}\n    </div>\n  );\n};\n\nexport default FastPacedAnimation;\n```",
              },
            },
            "BrowserHistoryScene.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, Sequence, spring } from 'remotion';\n\ntype BrowserHistorySceneProps = {\n  personImageUrl: string;\n  historyIcons: string[];\n  detectiveImageUrl: string;\n  sceneText: string;\n  animationDuration: number;\n  backgroundColor: string;\n};\n\nconst BrowserHistoryScene: React.FC<BrowserHistorySceneProps> = ({\n  personImageUrl,\n  historyIcons,\n  detectiveImageUrl,\n  sceneText,\n  animationDuration,\n  backgroundColor,\n}) => {\n  const frame = useCurrentFrame();\n  const iconAnimationProgress = spring({\n    frame,\n    fps: 30,\n    config: {\n      damping: 10,\n      stiffness: 100,\n    },\n  });\n\n  const iconTranslateY = interpolate(\n    iconAnimationProgress,\n    [0, 1],\n    [100, -100]\n  );\n\n  return (\n    <div\n      style={{\n        display: 'flex',\n        flexDirection: 'column',\n        alignItems: 'center',\n        justifyContent: 'center',\n        height: '100%',\n        backgroundColor,\n        position: 'relative',\n      }}\n    >\n      <img\n        src={personImageUrl}\n        alt=\"Person browsing\"\n        style={{\n          width: '200px',\n          height: 'auto',\n          zIndex: 1,\n        }}\n      />\n      <div\n        style={{\n          position: 'absolute',\n          top: '10%',\n          left: '10%',\n          right: '10%',\n          bottom: '10%',\n          display: 'flex',\n          flexWrap: 'wrap',\n          justifyContent: 'center',\n          alignItems: 'center',\n          zIndex: 0,\n        }}\n      >\n        {historyIcons.map((iconUrl, index) => (\n          <img\n            key={index}\n            src={iconUrl}\n            alt={`History icon ${index}`}\n            style={{\n              width: '50px',\n              height: '50px',\n              margin: '10px',\n              transform: `translateY(${iconTranslateY}px)`,\n              transition: `transform ${animationDuration}s ease-in-out`,\n            }}\n          />\n        ))}\n      </div>\n      <img\n        src={detectiveImageUrl}\n        alt=\"Detective figure\"\n        style={{\n          width: '100px',\n          height: 'auto',\n          position: 'absolute',\n          bottom: '10%',\n          right: '10%',\n          zIndex: 2,\n        }}\n      />\n      <div\n        style={{\n          position: 'absolute',\n          bottom: '5%',\n          left: '50%',\n          transform: 'translateX(-50%)',\n          color: '#fff',\n          fontSize: '24px',\n          textAlign: 'center',\n          zIndex: 3,\n        }}\n      >\n        {sceneText}\n      </div>\n    </div>\n  );\n};\n\nexport default BrowserHistoryScene;\n```",
              },
            },
            "DigitalTherapistOffice.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, Sequence } from 'remotion';\n\ntype DigitalTherapistOfficeProps = {\n  agentImageUrl: string;\n  humanImageUrl: string;\n  backgroundColor: string;\n  lighting: string;\n  animationTiming: number;\n  textContent: string;\n};\n\nconst DigitalTherapistOffice: React.FC<DigitalTherapistOfficeProps> = ({\n  agentImageUrl,\n  humanImageUrl,\n  backgroundColor,\n  lighting,\n  animationTiming,\n  textContent,\n}) => {\n  const frame = useCurrentFrame();\n  const noddingAnimation = interpolate(\n    frame,\n    [0, animationTiming * 30, animationTiming * 60],\n    [0, -10, 0],\n    {\n      extrapolateRight: 'clamp',\n    }\n  );\n\n  return (\n    <div\n      style={{\n        display: 'flex',\n        flexDirection: 'column',\n        alignItems: 'center',\n        justifyContent: 'center',\n        backgroundColor,\n        height: '100%',\n        width: '100%',\n        position: 'relative',\n        overflow: 'hidden',\n      }}\n    >\n      <div\n        style={{\n          position: 'absolute',\n          top: '10%',\n          left: '10%',\n          transform: `rotate(${noddingAnimation}deg)`,\n          transition: `transform ${animationTiming}s ease-in-out`,\n        }}\n      >\n        <img src={agentImageUrl} alt=\"AI Agent\" style={{ width: '150px', height: 'auto' }} />\n      </div>\n      <div\n        style={{\n          position: 'absolute',\n          top: '10%',\n          right: '10%',\n        }}\n      >\n        <img src={humanImageUrl} alt=\"Human\" style={{ width: '150px', height: 'auto' }} />\n      </div>\n      <div\n        style={{\n          position: 'absolute',\n          bottom: '10%',\n          textAlign: 'center',\n          color: lighting === 'soft' ? '#333' : '#fff',\n          fontSize: '24px',\n          padding: '10px',\n          backgroundColor: lighting === 'warm' ? 'rgba(255, 223, 186, 0.8)' : 'rgba(0, 0, 0, 0.5)',\n          borderRadius: '10px',\n        }}\n      >\n        {textContent}\n      </div>\n    </div>\n  );\n};\n\nexport default DigitalTherapistOffice;\n```",
              },
            },
            "EverydayAIApplications.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, Sequence } from 'remotion';\n\ntype Scene = {\n  imageUrl: string;\n  description: string;\n};\n\ntype AnimationTiming = {\n  duration: number;\n  delay: number;\n};\n\ntype ThemeColors = {\n  background: string;\n  text: string;\n};\n\ntype EverydayAIApplicationsProps = {\n  scenes: Scene[];\n  textContent: string;\n  animationTiming: AnimationTiming;\n  themeColors: ThemeColors;\n};\n\nconst EverydayAIApplications: React.FC<EverydayAIApplicationsProps> = ({\n  scenes,\n  textContent,\n  animationTiming,\n  themeColors,\n}) => {\n  const frame = useCurrentFrame();\n  const { duration, delay } = animationTiming;\n\n  return (\n    <div\n      style={{\n        flex: 1,\n        backgroundColor: themeColors.background,\n        color: themeColors.text,\n        display: 'flex',\n        flexDirection: 'column',\n        alignItems: 'center',\n        justifyContent: 'center',\n        padding: '20px',\n      }}\n    >\n      <h1\n        style={{\n          fontSize: '2em',\n          marginBottom: '20px',\n          opacity: interpolate(frame, [0, delay, delay + 30], [0, 0, 1]),\n        }}\n      >\n        {textContent}\n      </h1>\n      {scenes.map((scene, index) => {\n        const sceneStart = delay + index * duration;\n        const sceneEnd = sceneStart + duration;\n        const opacity = interpolate(\n          frame,\n          [sceneStart, sceneStart + 15, sceneEnd - 15, sceneEnd],\n          [0, 1, 1, 0]\n        );\n\n        return (\n          <Sequence key={index} from={sceneStart} durationInFrames={duration}>\n            <div\n              style={{\n                display: 'flex',\n                flexDirection: 'column',\n                alignItems: 'center',\n                marginBottom: '20px',\n                opacity,\n              }}\n            >\n              <img\n                src={scene.imageUrl}\n                alt={scene.description}\n                style={{\n                  width: '300px',\n                  height: 'auto',\n                  borderRadius: '10px',\n                  marginBottom: '10px',\n                }}\n              />\n              <p style={{ fontSize: '1.2em', textAlign: 'center' }}>\n                {scene.description}\n              </p>\n            </div>\n          </Sequence>\n        );\n      })}\n    </div>\n  );\n};\n\nexport default EverydayAIApplications;\n```",
              },
            },
            "VirtualConferenceTable.tsx": {
              file: {
                contents:
                  "```tsx\nimport React from 'react';\nimport { useCurrentFrame, interpolate, Sequence, Audio } from 'remotion';\n\ntype Avatar = {\n  name: string;\n  imageUrl: string;\n};\n\ntype VirtualConferenceTableProps = {\n  avatars: Avatar[];\n  tableColor: string;\n  animationTiming: number;\n  mood: string;\n  titleText: string;\n};\n\nconst VirtualConferenceTable: React.FC<VirtualConferenceTableProps> = ({\n  avatars,\n  tableColor,\n  animationTiming,\n  mood,\n  titleText,\n}) => {\n  const frame = useCurrentFrame();\n  const zoom = interpolate(frame, [0, animationTiming * 30], [1.5, 1], {\n    extrapolateRight: 'clamp',\n  });\n\n  const moodMusic = mood === 'excited' ? './assets/excited.mp3' : './assets/calm.mp3';\n\n  return (\n    <div\n      style={{\n        display: 'flex',\n        flexDirection: 'column',\n        alignItems: 'center',\n        justifyContent: 'center',\n        width: '100%',\n        height: '100%',\n        backgroundColor: '#f0f0f0',\n        overflow: 'hidden',\n      }}\n    >\n      <Audio src={moodMusic} />\n      <Sequence from={0}>\n        <h1\n          style={{\n            fontSize: '2em',\n            marginBottom: '20px',\n            transform: `scale(${zoom})`,\n            transition: `transform ${animationTiming}s ease-in-out`,\n          }}\n        >\n          {titleText}\n        </h1>\n      </Sequence>\n      <div\n        style={{\n          display: 'flex',\n          justifyContent: 'center',\n          alignItems: 'center',\n          width: '80%',\n          height: '60%',\n          backgroundColor: tableColor,\n          borderRadius: '50%',\n          position: 'relative',\n        }}\n      >\n        {avatars.map((avatar, index) => {\n          const angle = (index / avatars.length) * 2 * Math.PI;\n          const x = Math.cos(angle) * 150;\n          const y = Math.sin(angle) * 150;\n          return (\n            <div\n              key={avatar.name}\n              style={{\n                position: 'absolute',\n                left: `calc(50% + ${x}px)`,\n                top: `calc(50% + ${y}px)`,\n                transform: 'translate(-50%, -50%)',\n                textAlign: 'center',\n              }}\n            >\n              <img\n                src={avatar.imageUrl}\n                alt={avatar.name}\n                style={{\n                  width: '80px',\n                  height: '80px',\n                  borderRadius: '50%',\n                  border: '3px solid #fff',\n                }}\n              />\n              <p style={{ marginTop: '10px', fontSize: '0.8em' }}>{avatar.name}</p>\n            </div>\n          );\n        })}\n      </div>\n    </div>\n  );\n};\n\nexport default VirtualConferenceTable;\n```",
              },
            },
          },
        },
      },
    },
  },
  name: "AI Agents: The Basics in 60 Seconds",
  profile_id: "8ca7f1bc-35f7-4810-99de-58795c9697ff",
};
